services:
  app:
    image: node
    volumes:
      - ./public:/home/node
      - ./node_modules:/home/node/node_modules
    working_dir: /home/node
    command: node app/index
    environment:
      - GITHUB_CLIENT_ID=7fd147759a041a9bf61e
      - GITHUB_CLIENT_SECRET=09980c01cde46470b77974e1144d9c47fc43ad6b
    ports:
      - 3000:3000
  front:
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - 80:80